2019-01-11 10:58:23,493 [WARN ]  (AbstractClient.java.run:160) -  [DUBBO] client reconnect to 192.168.20.26:21884 find error . url: dubbo://192.168.20.26:21884/com.tscloud.address.domain.provider.IDistrictProvider?anyhost=true&application=address-admin-consumer-application&check=false&codec=dubbo&default.loadbalance=random&default.timeout=60000&dubbo=2.5.3&heartbeat=60000&interface=com.tscloud.address.domain.provider.IDistrictProvider&methods=getStreetno,getCommunity,findByMap,save,update,getVillage,findByPage,findAll,getLandmark,getRoad,getDistrict,findById,deleteById,findAllByPage,getBuilding&pid=13752&side=consumer&timestamp=1547175288395, dubbo version: 2.5.3, current host: 192.168.20.26
com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://192.168.20.26:21884/com.tscloud.address.domain.provider.IDistrictProvider?anyhost=true&application=address-admin-consumer-application&check=false&codec=dubbo&default.loadbalance=random&default.timeout=60000&dubbo=2.5.3&heartbeat=60000&interface=com.tscloud.address.domain.provider.IDistrictProvider&methods=getStreetno,getCommunity,findByMap,save,update,getVillage,findByPage,findAll,getLandmark,getRoad,getDistrict,findById,deleteById,findAllByPage,getBuilding&pid=13752&side=consumer&timestamp=1547175288395) failed to connect to server /192.168.20.26:21884, error message is:Connection refused: no further information
	at com.alibaba.dubbo.remoting.transport.netty.NettyClient.doConnect(NettyClient.java:124)
	at com.alibaba.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:280)
	at com.alibaba.dubbo.remoting.transport.AbstractClient$1.run(AbstractClient.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:384)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:354)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:276)
	... 3 more
